title: CFAI Centre - Formations OI
description: Portail des formations en Organisation Industrielle
theme: jekyll-theme-cayman

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Include/Exclude
include:
  - OI
